services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
    networks:
      - immich_default
      - backrest_default
      - adguard_default
      - uptime-kuma_default

networks:
  immich_default:
    external: true
  backrest_default:
    external: true
  adguard_default:
    external: true
  uptime-kuma_default:
    external: true
