services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "9898:9898"
    volumes:
      - ./data:/data
      - ./config:/config
      - ${HOME_DIR}/homelab:/source/homelab:ro
      - /mnt/backup:/backup
